<?php if($refs): ?>
    <div class="widget">
    <h4>Refereced items</h4>
        <div class="item-list">
        <?php foreach($refs as $ref): ?>
            <?php if($ref->item()): ?>
                <div class="referenced-item-list">
                    <a href="<?php echo $ref->item()->url(); ?>"><?php echo $ref->item()->displayTitle(); ?></a>
                    <?php if($ref->ref()): ?>
                        <span class="ref"><?php echo $ref->ref() ?></span>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

<style>
    .widget {
        margin: 0.5em;
        margin-top: 3em;
        padding: 1em;
        border-radius: 5px;
        background-color: rgba(0,0,0,0.04);        
    }
    .ref {
        margin-left: 1em;
        font-size: 0.9em;
    }
    .item-list {
        margin-top: 1em;
    }
</style>